baseURL = "https://bcaashka.com/"
languageCode = "en-us"
title = "bcaashka"
theme = "hesti"
paginate = 10
enableRobotsTXT = true
DefaultContentLanguage = "en"
googleAnalytics = ""
canonifyURLs = true
enableInlineShortcodes = true
[social]
    twitter = ""
    facebook = ""
[params]
    favicon = "favicon.ico"
    title = ""
    description = ""
    seoTitle = ""
    googleAdsense = ""
    image = ""
    locale = "en_US"
    thumbnail = "/assets/images/default-thumbnail.jpg"
[taxonomies]
    category = "categories"
[permalinks]
    categories = "/:slug/"
[sitemap]
    changefreq = "daily"
    filename = "sitemap.xml"
    priority = 0.5
[related]
    [[related.indices]]
        name  = "categories"
        weight = 80
    [[related.indices]]
        name  = "tags"
        weight = 100
[menu]
    [[menu.main]]
        identifier = "guides"
        name = "Guides"
        url = "/guides/"
        weight = 20