version: 2

jobs:
    build:
        docker:
            - image: node:10.15-alpine
        working_directory: ~/bcaashka
        steps:
            - run:
                name: Update git
                command: apk update && apk add git
            - run: git --version
            - run:
                name: Install OpenSSH
                command: apk update && apk add openssh
            - add_ssh_keys:
                fingerprint:
                    - "fa:bb:29:bb:e8:73:a1:41:53:ef:85:a3:e4:c1:c3:10"
            - run: git config --global user.email bot@bcaashka.com
            - run: git config --global user.name CircleCI
            - checkout
            - run:
                name: Checkout theme submodule
                command: git submodule sync && git submodule update --init --recursive
            - run:
                name: Install dependencies
                command: npm i
            - run:
                name: Install Hugo
                command: apk add hugo --update-cache --repository http://dl-3.alpinelinux.org/alpine/edge/community/ --allow-untrusted
            - run:
                name: Build Site
                command: npm run build
            - run:
                name: Publish Site
                command: npm run publish

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build:
          filters:
            branches:
              only: develop